### ISSUE TITLE
Issues with JSR310 causing crashes on many android versions

### ISSUE THREAD

**Issue by 7LPdWcaW** [nitrite/nitrite-java#249]
```
07-21 10:09:58.590 19814-19814/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:118)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at java.util.ServiceLoader$ServiceIterator.next(ServiceLoader.java:214)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1054)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1038)
        at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1088)
        at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:83)
        at org.dizitart.kno2.KNO2JacksonFacade.createObjectMapper(KNO2JacksonFacade.kt:39)
        at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:95)
        at org.dizitart.no2.mapper.JacksonFacade.<init>(JacksonFacade.java:63)
        at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.kt:36)
        at org.dizitart.kno2.KNO2JacksonMapper.<init>(KNO2JacksonMapper.kt:34)
        at org.dizitart.kno2.Builder.createNitriteBuilder$potassium_nitrite(Builder.kt:134)
        at org.dizitart.kno2.BuilderKt.nitrite(Builder.kt:166)
        at org.dizitart.kno2.BuilderKt.nitrite$default(Builder.kt:163)
```

I tried removing the dependancy 

```
api ('org.dizitart:potassium-nitrite:3.4.1') {
		exclude group: 'com.squareup.okhttp3'
		exclude group: 'com.fasterxml.jackson.datatype', module: 'jackson-datatype-jsr310'
}
```

but then I get 

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/fasterxml/jackson/datatype/jsr310/JavaTimeModule;
       at org.dizitart.kno2.KNO2JacksonFacade.createObjectMapper(KNO2JacksonFacade.java:42)
       at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:95)
       at org.dizitart.no2.mapper.JacksonFacade.<init>(JacksonFacade.java:63)
       at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.java:36)
       at org.dizitart.kno2.KNO2JacksonMapper.<init>(KNO2JacksonMapper.java:34)
       at org.dizitart.kno2.Builder.createNitriteBuilder$potassium_nitrite(Builder.java:134)
       at org.dizitart.kno2.BuilderKt.nitrite(BuilderKt.java:166)
       at org.dizitart.kno2.BuilderKt.nitrite$default(BuilderKt.java:163)
```

So I provide my own mapper using 

```
open class NitriteFacade(modules: Set<Module>? = setOf()) : JacksonFacade(modules)
{
	override fun createObjectMapper(): ObjectMapper
	{
		val objectMapper = super.createObjectMapper()
		objectMapper.registerModule(KotlinModule())
//		objectMapper.registerModule(JavaTimeModule())
		objectMapper.registerModule(JodaModule())
		objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
		return objectMapper
	}
}
```

but this throws errors 

```
07-21 10:22:26.170 20706-20706/ E/AndroidRuntime: FATAL EXCEPTION: main
    org.dizitart.no2.exceptions.IndexingException: NO2.5020: invalid type specified java.lang.String for indexing
        at org.dizitart.no2.util.ValidationUtils.validateObjectIndexField(ValidationUtils.java:233)
        at org.dizitart.no2.util.ObjectUtils.getIdField(ObjectUtils.java:148)
        at org.dizitart.no2.objects.DefaultObjectRepository.createIndexes(DefaultObjectRepository.java:315)
        at org.dizitart.no2.objects.DefaultObjectRepository.initRepository(DefaultObjectRepository.java:303)
        at org.dizitart.no2.objects.DefaultObjectRepository.<init>(DefaultObjectRepository.java:57)
        at org.dizitart.no2.objects.RepositoryFactory.open(RepositoryFactory.java:46)
        at org.dizitart.no2.Nitrite.getRepository(Nitrite.java:140)
``` 

How is this supposed to be compatible with android api 19+ when it includes dependencies for Java8 time? even when I have the 

```
compileOptions {
		sourceCompatibility = JavaVersion.VERSION_1_8
		targetCompatibility = JavaVersion.VERSION_1_8
}
``` 

set i still get problems

**Comment by 7LPdWcaW** [comment]
I _may_ have solved it using `nitriteMapper = KNO2JacksonMapper(NitriteFacade())` instead of `nitriteMapper = GenericMapper(NitriteFacade())`

**Comment by anidotnet** [comment]
If you are using potassium-nitrite in your kotlin project, use nitrite builder dsl. You can find one example here - https://github.com/nitrite/nitrite-java/blob/c3efcf69b6a7104bc6f5ffb12ef3e4ef09eefe4d/potassium-nitrite/src/test/kotlin/org/dizitart/kno2/NitriteTest.kt#L45

If you are using threetenbp backport, you can find one example here - https://github.com/nitrite/nitrite-java/blob/master/potassium-nitrite/src/test/kotlin/org/dizitart/kno2/BackportJavaTimeTest.kt

Finally please update to latest version 3.4.2, it has latest version of kotlin dependencies.

**Comment by 7LPdWcaW** [comment]
Yes i am using the builder.

The out of the box functionality does not work on earlier apis (but the README says) because of jackson's module registration with java 8 time apis

**Comment by anidotnet** [comment]
OK, so if you don't need jdk8 or jsr310 module, then you should be good with custom KNO2JacksonMapper() and excluding those dependencies.

**Comment by 7LPdWcaW** [comment]
I have posted my solution here in case anyone else has this same issue with Java8 time module.
