### ISSUE TITLE
Compatibility with GraalVM

### ISSUE THREAD

**Issue by Gillani0** [nitrite/nitrite-java#403]
Hi,
I'd love to use this awsome library with the native graalVM support. 

Currently I'm fixing the similar issue as described [here](https://github.com/oracle/graal/issues/1074). Following are my error logs:

```Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Detailed message:
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@45c5e218 reached by 
        scanning method org.dizitart.no2.Security.getNextSalt(Security.java:140)
Call path from entry point to org.dizitart.no2.Security.getNextSalt(): 
        at org.dizitart.no2.Security.getNextSalt(Security.java:139)
        at org.dizitart.no2.Security.createSecurely(Security.java:59)
        at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:459)
        at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:415)
        at com.wattsense.config.DbTemplate.init(DbTemplate.kt:37)
        at com.wattsense.config.DbTemplate.onStart(DbTemplate.kt:22)
        at com.wattsense.config.DbTemplate_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(DbTemplate_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$DeferredEventNotification.run(EventImpl.java:426)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:141)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Detailed message:
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@45c5e218 reached by 
        scanning method org.dizitart.no2.Security.getNextSalt(Security.java:140)
Call path from entry point to org.dizitart.no2.Security.getNextSalt(): 
        at org.dizitart.no2.Security.getNextSalt(Security.java:139)
        at org.dizitart.no2.Security.createSecurely(Security.java:59)
        at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:459)
        at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:415)
        at com.wattsense.config.DbTemplate.init(DbTemplate.kt:37)
        at com.wattsense.config.DbTemplate.onStart(DbTemplate.kt:22)
        at com.wattsense.config.DbTemplate_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(DbTemplate_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$DeferredEventNotification.run(EventImpl.java:426)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:141)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

 ```

**Comment by anidotnet** [comment]
I have not tested it with GraalVM. But any community contribution is more than welcome.

**Comment by anidotnet** [comment]
Have you got any progress on this issue?

**Comment by DarkAtra** [comment]
Hey @anidotnet,
are you still open for contributions here? I was actually using version 3.x of nitrite (with mvstore) with graalvm in my project. [There were only a few runtime hints required for it to work](https://github.com/DarkAtra/v-rising-discord-bot/blob/9ad4c0b04313fb3423e6641413803695d0032e58/src/main/kotlin/de/darkatra/vrising/discord/BotRuntimeHints.kt#L44-L62) - most of them were related to java serialization. Version 4.x likely requires the same or at least somehwat similar runtime hints.

**Comment by anidotnet** [comment]
@DarkAtra contribution is always welcome in latest Nitrite.

**Comment by DarkAtra** [comment]
> @DarkAtra contribution is always welcome in latest Nitrite.

After looking at the tests a bit, it's rather unlikely that i'm able to also introduce tests for nitrite mvstore as still uses junit 4. I've never tested graalvm with junit 4 before and already noticed that annotations like `@DisabledInNativeImage` are missing. Also, quite a few tests are currently failing on my machine due to https://github.com/nitrite/nitrite-java/issues/994.

Regarding the native hints: it seems like the following configuration is required for nitrite to properly read and write in a native image (when using mvstore with custom `EntityConverter`s:

<details>
<summary>serialization-config.json</summary>
<p>
<pre>
[
    {
        "name": "java.lang.Integer"
    },
    {
        "name": "java.lang.Long"
    },
    {
        "name": "java.lang.Number"
    },
    {
        "name": "java.lang.String"
    },
    {
        "name": "java.util.ArrayList"
    },
    {
        "name": "java.util.concurrent.atomic.AtomicBoolean"
    },
    {
        "name": "java.util.concurrent.ConcurrentHashMap"
    },
    {
        "name": "java.util.concurrent.ConcurrentHashMap$Segment"
    },
    {
        "name": "java.util.concurrent.CopyOnWriteArrayList"
    },
    {
        "name": "java.util.concurrent.locks.AbstractOwnableSynchronizer"
    },
    {
        "name": "java.util.concurrent.locks.AbstractQueuedSynchronizer"
    },
    {
        "name": "java.util.concurrent.locks.ReentrantLock"
    },
    {
        "name": "java.util.concurrent.locks.ReentrantLock$NonfairSync"
    },
    {
        "name": "java.util.concurrent.locks.ReentrantLock$Sync"
    },
    {
        "name": "java.util.HashMap"
    },
    {
        "name": "java.util.HashSet"
    },
    {
        "name": "java.util.LinkedHashMap"
    },
    {
        "name": "org.dizitart.no2.collection.NitriteDocument"
    },
    {
        "name": "org.dizitart.no2.collection.NitriteId"
    },
    {
        "name": "org.dizitart.no2.common.DBValue"
    },
    {
        "name": "org.dizitart.no2.common.Fields"
    },
    {
        "name": "org.dizitart.no2.common.meta.Attributes"
    },
    {
        "name": "org.dizitart.no2.common.tuples.Pair"
    },
    {
        "name": "org.dizitart.no2.index.IndexDescriptor"
    },
    {
        "name": "org.dizitart.no2.index.IndexMeta"
    },
    {
        "name": "org.dizitart.no2.store.UserCredential"
    }
]
</pre>
</p>
</details>

Also, **users will have to provide additional reflection hints for classes that they use repositories for**.

For example, if i was to store the following `Error` class:

```kotlin
package de.darkatra

import java.time.Instant

data class Error(
    val message: String,
    val timestamp: Instant
)
```

using the following entity converter:

```kotlin
class ErrorEntityConverter : EntityConverter<Error> {

    override fun getEntityType(): Class<Error> = Error::class.java

    override fun fromDocument(document: Document, nitriteMapper: NitriteMapper): Error {
        return Error(
            message = document.get(Error::message.name, String::class.java),
            timestamp = Instant.parse(document.get(Error::timestamp.name, String::class.java))
        )
    }

    override fun toDocument(error: Error, nitriteMapper: NitriteMapper): Document {
        return Document.createDocument().apply {
            put(Error::message.name, error.message)
            put(Error::timestamp.name, error.timestamp.toString())
        }
    }
}
```

via:

```kotlin
val repository = database.getRepository(Error::class.java)
repository.insert(
  Error(
    message = "message",
    timestamp = Instant.now()
  )
)
```

I'd have to add the following `reflect-config.json`:
```
{
  "name": "de.darkatra.Error",
  "allDeclaredFields": true
}
```

or i'd get the following error message:

```
org.dizitart.no2.exceptions.ValidationException: No such field 'message' for type de.darkatra.Error
        at org.dizitart.no2.repository.Reflector.getField(Reflector.java:127) ~[na:na]
        at org.dizitart.no2.repository.AnnotationScanner.populateIndex(AnnotationScanner.java:156) ~[na:na]
        at org.dizitart.no2.repository.AnnotationScanner.scanIndicesAnnotation(AnnotationScanner.java:95) ~[na:na]
        at org.dizitart.no2.repository.AnnotationScanner.performScan(AnnotationScanner.java:71) ~[na:na]
        at org.dizitart.no2.repository.RepositoryOperations.scanIndexes(RepositoryOperations.java:65) ~[na:na]
        at org.dizitart.no2.repository.DefaultObjectRepository.initialize(DefaultObjectRepository.java:239) ~[na:na]
        at org.dizitart.no2.repository.DefaultObjectRepository.<init>(DefaultObjectRepository.java:55) ~[na:na]
        at org.dizitart.no2.repository.RepositoryFactory.createRepository(RepositoryFactory.java:145) ~[na:na]
        at org.dizitart.no2.repository.RepositoryFactory.getRepository(RepositoryFactory.java:78) ~[na:na]
        at org.dizitart.no2.repository.RepositoryFactory.getRepository(RepositoryFactory.java:52) ~[na:na]
        at org.dizitart.no2.NitriteDatabase.getRepository(NitriteDatabase.java:73) ~[na:na]
```
