### ISSUE TITLE
get ObjectRespository on nitritite 4.0.0

### ISSUE THREAD

**Issue by tmoliveira** [nitrite/nitrite-java#412]
Hi,

I am testing nitrite 4.0.0. If I run my test without an ObjectRepository already created, everything went well. However, if the database is already created and I re-start the JVM, I get the following error when getting the ObjectRepository (the same happens if I use directly a nitriteCollection).

Exception in thread "main" org.dizitart.no2.exceptions.NitriteIOException: failed to write key and value
	at org.dizitart.no2.rocksdb.RocksDBMap.put(RocksDBMap.java:162)
	at org.dizitart.no2.repository.RepositoryFactory.writeCatalog(RepositoryFactory.java:125)
	at org.dizitart.no2.repository.RepositoryFactory.createRepository(RepositoryFactory.java:113)
	at org.dizitart.no2.repository.RepositoryFactory.getRepository(RepositoryFactory.java:77)
	at org.dizitart.no2.repository.RepositoryFactory.getRepository(RepositoryFactory.java:51)
	at org.dizitart.no2.NitriteDatabase.getRepository(NitriteDatabase.java:81)
	at mavenTest.mavenTest.NitriteTest.main(NitriteTest.java:67)
Caused by: org.dizitart.no2.exceptions.NitriteIOException: failed to query by key
	at org.dizitart.no2.rocksdb.RocksDBMap.get(RocksDBMap.java:81)
	at org.dizitart.no2.store.NitriteMap.updateLastModifiedTime(NitriteMap.java:199)
	at org.dizitart.no2.rocksdb.RocksDBMap.put(RocksDBMap.java:159)
	... 6 more
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 17
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:167)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802)
	at org.dizitart.no2.rocksdb.formatter.NitriteSerializers$AttributesSerializer.read(NitriteSerializers.java:162)
	at org.dizitart.no2.rocksdb.formatter.NitriteSerializers$AttributesSerializer.read(NitriteSerializers.java:152)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:710)
	at org.dizitart.no2.rocksdb.formatter.KryoObjectFormatter.decode(KryoObjectFormatter.java:91)
	at org.dizitart.no2.rocksdb.RocksDBMap.get(RocksDBMap.java:78)
	... 8 more

Is there something else I need to do besides db.getRepository(ValueObject.class)?

Thanks

**Comment by anidotnet** [comment]
Sorry for belated reply. Yes this is a bug. I'll fix it shortly.

**Comment by tmoliveira** [comment]
Thanks for your response @anidotnet !

One more question about the update operation on Nitrite. It is possible to update specific object/document field(s) without reading the entire object, change the desired field, and updating the entire object again?

Thanks one more time.

**Comment by anidotnet** [comment]
Nope. It reads whole document before update.

**Comment by tmoliveira** [comment]
But nitrite does already that in it's internals, or should we do that in our application logic? I am using the ObjectRepository with Mappable objects and I did not find a way to update only specific fields at a time. I suppose that its application responsibility to read the object, update the required fields, and update all the object; is this correct? Or there is a way to give nitrite the fields to be update and then it read-update-write the object?

Thanks again @anidotnet, and let me know when the bug mentioned in the first comment is fixed :-)

**Comment by anidotnet** [comment]
Are you looking for this method - `WriteResult update(Filter filter, Document update, boolean justOnce)` ? Here the document `update` contains the field to be updated and its new value and `filter` is used to select the element from the repository to update.

I already fixed the original issue when this issue was closed and it is available in 4.0.0 snapshot.

**Comment by tmoliveira** [comment]
Thanks @anidotnet for the support, that was exactly what I was looking for. The document may contains only a subset of fields, and only these fields will be update. I have already tested it.
