### ISSUE TITLE
Datagate crash on startup

### ISSUE THREAD

**Issue by ichbintobias2** [nitrite/nitrite-java#436]
When I try to run datagate.bat the service tries to start but crashes shortly after. To me it seems like there is a missing dependency (?) in the zip file which I downloaded from the release page here on GitHub. Operating system is Windows 10, MongoDB runs in a Docker container on localhost:27017. The full logs are as follows:
```
2021-01-26 21:33:59.052  INFO 8700 --- [main] o.dizitart.no2.datagate.NitriteDataGate  : Starting NitriteDataGate on DESKTOP-RDGOHO0 with PID 8700 (C:\Users\Tobias\Downloads\Datagate\lib\nitrite-datagate.jar started by Tobias in C:\Users\Tobias\Downloads\Datagate\bin)
2021-01-26 21:33:59.060  INFO 8700 --- [main] o.dizitart.no2.datagate.NitriteDataGate  : No active profile set, falling back to default profiles: default
2021-01-26 21:34:03.656  INFO 8700 --- [main] org.eclipse.jetty.util.log               : Logging initialized @6455ms to org.eclipse.jetty.util.log.Slf4jLog
2021-01-26 21:34:04.015  INFO 8700 --- [main] org.eclipse.jetty.server.Server          : jetty-9.4.7.v20170914
2021-01-26 21:34:04.332  INFO 8700 --- [main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2021-01-26 21:34:04.332  INFO 8700 --- [main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2021-01-26 21:34:04.337  INFO 8700 --- [main] org.eclipse.jetty.server.session         : Scavenging every 660000ms
2021-01-26 21:34:04.350  INFO 8700 --- [main] o.e.j.s.h.C.Nitrite_DataGate             : Initializing Spring embedded WebApplicationContext
2021-01-26 21:34:04.594  INFO 8700 --- [main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.c.e.j.JettyEmbeddedWebAppContext@59221b97{/datagate,[file:///C:/Users/Tobias/AppData/Local/Temp/jetty-docbase.14223249952001795079.8080/, jar:file:/C:/Users/Tobias/Downloads/Datagate/lib/nitrite-datagate.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],AVAILABLE}
2021-01-26 21:34:04.610  INFO 8700 --- [main] org.eclipse.jetty.server.Server          : Started @7413ms
2021-01-26 21:34:05.064  INFO 8700 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2021-01-26 21:34:05.222  INFO 8700 --- [cluster-ClusterId{value='60107cbd5dab3a0b4bbcda03', description='null'}-127.0.0.1:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:1}] to 127.0.0.1:27017
2021-01-26 21:34:05.236  INFO 8700 --- [cluster-ClusterId{value='60107cbd5dab3a0b4bbcda03', description='null'}-127.0.0.1:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 3]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=8249900}
2021-01-26 21:34:05.440  INFO 8700 --- [main] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:2}] to 127.0.0.1:27017
2021-01-26 21:34:05.845  INFO 8700 --- [main] o.e.j.s.h.C.Nitrite_DataGate             : jolokia: No access restrictor found, access to any MBean is allowed
2021-01-26 21:34:07.671  INFO 8700 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2021-01-26 21:34:08.933  INFO 8700 --- [main] org.eclipse.jetty.server.Server          : jetty-9.4.7.v20170914
2021-01-26 21:34:08.933  INFO 8700 --- [main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2021-01-26 21:34:08.933  INFO 8700 --- [main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2021-01-26 21:34:08.933  INFO 8700 --- [main] org.eclipse.jetty.server.session         : Scavenging every 600000ms
2021-01-26 21:34:08.933  INFO 8700 --- [main] o.e.j.s.h.C.Nitrite_DataGate             : Initializing Spring embedded WebApplicationContext
2021-01-26 21:34:08.949  INFO 8700 --- [main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.c.e.j.JettyEmbeddedWebAppContext@37b56ac7{/,[file:///C:/Users/Tobias/AppData/Local/Temp/jetty-docbase.8611097571263871156.9091/, jar:file:/C:/Users/Tobias/Downloads/Datagate/lib/nitrite-datagate.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],AVAILABLE}
2021-01-26 21:34:08.949  INFO 8700 --- [main] org.eclipse.jetty.server.Server          : Started @11758ms
2021-01-26 21:34:09.061  INFO 8700 --- [main] org.eclipse.jetty.server.session         : Stopped scavenging
2021-01-26 21:34:09.068  INFO 8700 --- [main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.c.e.j.JettyEmbeddedWebAppContext@37b56ac7{/,[file:///C:/Users/Tobias/AppData/Local/Temp/jetty-docbase.8611097571263871156.9091/, jar:file:/C:/Users/Tobias/Downloads/Datagate/lib/nitrite-datagate.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}
2021-01-26 21:34:09.075  INFO 8700 --- [main] org.eclipse.jetty.server.session         : Stopped scavenging
2021-01-26 21:34:09.076  INFO 8700 --- [main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.c.e.j.JettyEmbeddedWebAppContext@59221b97{/datagate,[file:///C:/Users/Tobias/AppData/Local/Temp/jetty-docbase.14223249952001795079.8080/, jar:file:/C:/Users/Tobias/Downloads/Datagate/lib/nitrite-datagate.jar!/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}
2021-01-26 21:34:09.100 ERROR 8700 --- [main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'halMessageConverterSupportedMediaTypeCustomizer': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/hateoas/mvc/TypeConstrainedMappingJackson2HttpMessageConverter
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.createChildManagementContext(EndpointWebMvcAutoConfiguration.java:193) ~[spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.afterSingletonsInstantiated(EndpointWebMvcAutoConfiguration.java:156) ~[spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.dizitart.no2.datagate.NitriteDataGate.main(NitriteDataGate.java:79) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[nitrite-datagate.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[nitrite-datagate.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[nitrite-datagate.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[nitrite-datagate.jar:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/hateoas/mvc/TypeConstrainedMappingJackson2HttpMessageConverter
	at org.springframework.boot.autoconfigure.hateoas.HypermediaHttpMessageConverterConfiguration$HalMessageConverterSupportedMediaTypesCustomizer.configureHttpMessageConverter(HypermediaHttpMessageConverterConfiguration.java:83) ~[spring-boot-autoconfigure-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.autoconfigure.hateoas.HypermediaHttpMessageConverterConfiguration$HalMessageConverterSupportedMediaTypesCustomizer.configureHttpMessageConverters(HypermediaHttpMessageConverterConfiguration.java:77) ~[spring-boot-autoconfigure-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at org.springframework.boot.autoconfigure.hateoas.HypermediaHttpMessageConverterConfiguration$HalMessageConverterSupportedMediaTypesCustomizer.configureHttpMessageConverters(HypermediaHttpMessageConverterConfiguration.java:67) ~[spring-boot-autoconfigure-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.hateoas.mvc.TypeConstrainedMappingJackson2HttpMessageConverter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[nitrite-datagate.jar:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 42 common frames omitted
```

Otherwise loving Nitrite db so far!

**Comment by anidotnet** [comment]
Could you please try this on jdk-8?

**Comment by ichbintobias2** [comment]
Thank you so much for the quick reply! I was on Java 11 with an AdoptOpenJDK distribution. I would not have thought that this would cause problems but changing the JAVA_HOME system variable to Oracle 1.8 version did in fact solve the issue.
