### ISSUE TITLE
Crash on Document.put("key", List<? extends Mappable>)

### ISSUE THREAD

**Issue by Doc1faux** [nitrite/nitrite-java#550]
Hi,

As previous issues #168 & #206, I'm experiencing a crash when I attempt to insert an object implementing the `Mappable` interface and containing a list of objects implementing also the `Mappable` interface.
There is no such use case in the documentation but in issue #168, the suggested method was to use `Document.put("key", List<? extends Mappable>)` which crashes.
Here is the stacktrace where we can see that Nitrite handles well both primitive object and list, embedded object implementing `Mappable` interface but not list of them, ended up in the stacktrace as references and not object content.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sebastienvitard.nitritemappablelist, PID: 23222
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sebastienvitard.nitritemappablelist/com.sebastienvitard.nitritemappablelist.MainActivity}: java.lang.IllegalStateException: java.lang.IllegalArgumentException: Could not serialize {primitiveObject=Test 1, primiviteList=[Test1, Test2, Test3], embeddedObject={primitiveObject=Test, primiviteList=[Test1, Test2, Test3]}, embeddedList=[com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@65064a8, com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@dc08b8a, com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@c3ba5fb], _id=196484816964670, _revision=1, _modified=1622789776233} [1.4.200/0] [1.4.200/3]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: java.lang.IllegalArgumentException: Could not serialize {primitiveObject=Test 1, primiviteList=[Test1, Test2, Test3], embeddedObject={primitiveObject=Test, primiviteList=[Test1, Test2, Test3]}, embeddedList=[com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@65064a8, com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@dc08b8a, com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@c3ba5fb], _id=196484816964670, _revision=1, _modified=1622789776233} [1.4.200/0] [1.4.200/3]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.store(MVStore.java:1338)
        at org.h2.mvstore.MVStore.store(MVStore.java:1312)
        at org.h2.mvstore.MVStore.commit(MVStore.java:1303)
        at org.dizitart.no2.store.NitriteMVStore.commit(NitriteMVStore.java:69)
        at org.dizitart.no2.Nitrite.commit(Nitrite.java:266)
        at com.sebastienvitard.nitritemappablelist.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.IllegalArgumentException: Could not serialize {primitiveObject=Test 1, primiviteList=[Test1, Test2, Test3], embeddedObject={primitiveObject=Test, primiviteList=[Test1, Test2, Test3]}, embeddedList=[com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@65064a8, com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@dc08b8a, com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject@c3ba5fb], _id=196484816964670, _revision=1, _modified=1622789776233} [1.4.200/0]
        at org.h2.mvstore.DataUtils.newIllegalArgumentException(DataUtils.java:924)
        at org.h2.mvstore.type.ObjectDataType.serialize(ObjectDataType.java:359)
        at org.h2.mvstore.type.ObjectDataType$SerializedObjectType.write(ObjectDataType.java:1527)
        at org.h2.mvstore.type.ObjectDataType.write(ObjectDataType.java:127)
        at org.h2.mvstore.type.ObjectDataType.write(ObjectDataType.java:121)
        at org.h2.mvstore.Page$Leaf.writeValues(Page.java:1516)
        at org.h2.mvstore.Page.write(Page.java:670)
        at org.h2.mvstore.Page$Leaf.writeUnsavedRecursive(Page.java:1525)
E/AndroidRuntime:     at org.h2.mvstore.MVStore.storeNow(MVStore.java:1427)
        at org.h2.mvstore.MVStore.store(MVStore.java:1334)
        	... 20 more
     Caused by: java.io.NotSerializableException: com.sebastienvitard.nitritemappablelist.MappableEmbeddedObject
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1434)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1230)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
        at java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:357)
        at java.util.HashMap.writeObject(HashMap.java:1366)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
        at org.h2.mvstore.type.ObjectDataType.serialize(ObjectDataType.java:356)
        	... 28 more
```
Here are my objects:
```
public class MappableObject implements Mappable
{
    private static final String PRIMITIVE_OBJECT_KEY = "primitiveObject";
    private static final String PRIMITIVE_LIST_KEY = "primiviteList";
    private static final String EMBEDDED_OBJECT_KEY = "embeddedObject";
    private static final String EMBEDDED_LIST_KEY = "embeddedList";

    @Id
    private String primitiveObject;
    private List<String> primiviteList;
    private MappableEmbeddedObject embeddedObject;
    private List<MappableEmbeddedObject> embeddedList;

    public MappableObject() { }

    public MappableObject(String primitiveObject)
    {
        this.primitiveObject = primitiveObject;
        this.primiviteList = Arrays.asList("Test1", "Test2", "Test3");
        this.embeddedObject = new MappableEmbeddedObject(primitiveObject);
        this.embeddedList = Arrays.asList(new MappableEmbeddedObject("Test1"),
                new MappableEmbeddedObject("Test2"),
                new MappableEmbeddedObject("Test3"));
    }

    @Override
    public Document write(NitriteMapper mapper)
    {
        Document document = new Document();
        document.put(PRIMITIVE_OBJECT_KEY, primitiveObject);
        document.put(PRIMITIVE_LIST_KEY, primiviteList);
        document.put(EMBEDDED_OBJECT_KEY, embeddedObject.write(mapper));
        document.put(EMBEDDED_LIST_KEY, embeddedList);
        return document;
    }

    @Override
    public void read(NitriteMapper mapper, Document document)
    {
        if (document != null)
        {
            primitiveObject = (String) document.get(PRIMITIVE_OBJECT_KEY);
            primiviteList = (List<String>) document.get(PRIMITIVE_LIST_KEY);
            Document embeddedDocument = (Document) document.get(EMBEDDED_OBJECT_KEY);
            if (embeddedDocument != null)
            {
                embeddedObject = new MappableEmbeddedObject();
                embeddedObject.read(mapper, embeddedDocument);
            }
            embeddedList = (List<MappableEmbeddedObject>) document.get(EMBEDDED_LIST_KEY);
        }
    }
}
```
```
public class MappableEmbeddedObject implements Mappable
{
    private static final String PRIMITIVE_OBJECT_KEY = "primitiveObject";
    private static final String PRIMITIVE_LIST_KEY = "primiviteList";

    private String primitiveObject;
    private List<String> primiviteList;

    public MappableEmbeddedObject() { }

    public MappableEmbeddedObject(String primitiveObject)
    {
        this.primitiveObject = primitiveObject;
        this.primiviteList = Arrays.asList("Test1", "Test2", "Test3");
    }

    @Override
    public Document write(NitriteMapper mapper)
    {
        Document document = new Document();
        document.put(PRIMITIVE_OBJECT_KEY, primitiveObject);
        document.put(PRIMITIVE_LIST_KEY, primiviteList);
        return document;
    }

    @Override
    public void read(NitriteMapper mapper, Document document)
    {
        if (document != null)
        {
            primitiveObject = (String) document.get(PRIMITIVE_OBJECT_KEY);
            primiviteList = (List<String>) document.get(PRIMITIVE_LIST_KEY);
        }
    }
}
```

Maybe Nitrite cannot handle an embedded list of objects implementing the `Mappable` interface or I'm doing it wrong?
For info, I'm developing an Android app with this setup:

- Nitrite version: 3.4.2
- target SDK version: 30 (latest)
- min SDK version: 19 (4.4)
- build tools version : 30.0.3 (latest)
- Java version: 8
- Gradle version: 4.2.0
- Android Studio version: 4.2
- OS: Ubuntu 20.04
- Testing device: Pixel 3 running Android 11 build RQ2A.210505.002

**Comment by Doc1faux** [comment]
After diving into the issue, it seems that is not Nitrite which is involved in this case but serialization of custom objects contained in the embedded list.
The `Mappable` interface is not sufficient by itself, we need to implement also the `Serializable` interface for these objects and their descendants which is called in the serialization process of a list of custom objects.
I was expecting Nitrite to handle the serialization by itself with the `Mappable` interface but it seems not to be the case.
I hope it will not imply side effects on query filters and sorting 🤞

**Comment by anidotnet** [comment]
The `Mappable` interface is to help manually driving the serialization. Its job is to delegate the serialization to the programmer. In your case, you are not serializing `List<MappableEmbeddedObject>` properly. You need to convert `List<MappableEmbeddedObject>` into `List<Document>` manually and then call `document.put(EMBEDDED_LIST_KEY, embeddedList);`. It is similar what you are doing for EMBEDDED_OBJECT_KEY field.

**Comment by Doc1faux** [comment]
Oh, you're right, I did not think about it that way!
Thanks a lot for your fast reply ;)

As I did in #549, I share below some methods to serialize/deserialize lists of generic objets implementing the `Mappable` interface:
```
    @Nullable
    public static <T extends Mappable> List<Document> toDocumentsList(@NonNull NitriteMapper mapper,
                                                                      @Nullable List<T> elementsList)
    {
        List<Document> documentsList = null;
        if (elementsList != null)
        {
            documentsList = new ArrayList<>(elementsList.size());
            for (T element : elementsList)
            {
                documentsList.add(element.write(mapper));
            }
        }
        return documentsList;
    }

    @Nullable
    public static <T extends Mappable> List<T> toElementsList(@NonNull NitriteMapper mapper,
                                                              @Nullable List<Document> documentsList,
                                                              Class<T> typeOfElement)
            throws InstantiationException, IllegalAccessException
    {
        List<T> elementsList = null;
        if (documentsList != null)
        {
            elementsList = new ArrayList<>(documentsList.size());
            for (Document document : documentsList)
            {
                T element = typeOfElement.newInstance();
                element.read(mapper, document);
                elementsList.add(element);
            }
        }
        return elementsList;
    }
```

Usage:
```
    @Override
    public Document write(NitriteMapper mapper)
    {
        Document document = new Document();
        document.put("key", toDocumentsList(mapper, objectsList));
        return document;
    }

    @Override
    public void read(NitriteMapper mapper, Document document)
    {
        if (document != null)
        {
            List<Document> objectsDocument = (List<Document>) document.get("key");
            try
            {
                objectsList = toElementsList(mapper, objectsDocument, MyObjet.class);
            }
            catch (InstantiationException | IllegalAccessException ignored) { }
        }
    }
```

I may need equivalent methods for Map<String, MyObject>. If so, I will share them again ;)
