### ISSUE TITLE
4.0.1 - Issue with repo entities - Object must implements Mappable?

### ISSUE THREAD

**Issue by ThraaxSession** [nitrite/nitrite-java#680]
Hi!
I've following issue when I want to create data:

This is my repo object.

```kotlin
import org.dizitart.no2.index.IndexType
import org.dizitart.no2.repository.annotations.Entity
import org.dizitart.no2.repository.annotations.Id
import org.dizitart.no2.repository.annotations.Index

@Entity(
    value = "server",
    indices = [Index(value = ["installed"], type = IndexType.UNIQUE)]
)
data class Server(
    @Id
    val installed: Boolean = false
)
```

But when I want to insert data, I get this exception:
```kotlin
val serverRepo = db.getRepository(Server::class.java)
val serverDto = Server(true)
serverRepo.update(serverDto)
```

```
org.dizitart.no2.exceptions.ObjectMappingException: object must implements Mappable
	at org.dizitart.no2.common.mapper.MappableMapper.convertToDocument(MappableMapper.java:85) ~[nitrite-4.0.1-SNAPSHOT.jar:?]
	at org.dizitart.no2.common.mapper.MappableMapper.convert(MappableMapper.java:108) ~[nitrite-4.0.1-SNAPSHOT.jar:?]
	at org.dizitart.no2.repository.RepositoryOperations.toDocument(RepositoryOperations.java:119) ~[nitrite-4.0.1-SNAPSHOT.jar:?]
	at org.dizitart.no2.repository.RepositoryOperations.toDocuments(RepositoryOperations.java:105) ~[nitrite-4.0.1-SNAPSHOT.jar:?]
	at org.dizitart.no2.repository.DefaultObjectRepository.insert(DefaultObjectRepository.java:108) ~[nitrite-4.0.1-SNAPSHOT.jar:?]
	at org.dizitart.no2.repository.ObjectRepository.insert(ObjectRepository.java:119) ~[nitrite-4.0.1-SNAPSHOT.jar:?]
```

**Comment by anidotnet** [comment]
Please either refer to the document [here](https://www.dizitart.org/nitrite-database/#mappable) or the junit test classes available in the repo.
