### ISSUE TITLE
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

### ISSUE THREAD

**Issue by bahmanebazoo** [nitrite/nitrite-java#714]
Hi this is my code as your template:

    private val nitriteDatabase = nitrite {
        file = File(application.filesDir, "database")
        autoCommitBufferSize = 2048
        compress = true
        autoCompact = false
    }

and this is my logcat in android studio:

    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:118)
        at java.lang.Class.newInstance(Native Method)
        at java.util.ServiceLoader$ServiceIterator.next(ServiceLoader.java:214)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1054)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1038)
        at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1088)
        at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:83)
        at org.dizitart.kno2.KNO2JacksonFacade.createObjectMapper(KNO2JacksonFacade.kt:39)
        at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:95)
        at org.dizitart.no2.mapper.JacksonFacade.<init>(JacksonFacade.java:63)
        at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.kt:36)
        at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.kt:36)
        at org.dizitart.kno2.KNO2JacksonMapper.<init>(KNO2JacksonMapper.kt:33)
        at org.dizitart.kno2.Builder.createNitriteBuilder$potassium_nitrite(Builder.kt:132)
        at org.dizitart.kno2.BuilderKt.nitrite(Builder.kt:166)
        at org.dizitart.kno2.BuilderKt.nitrite$default(Builder.kt:163)

**Comment by anidotnet** [comment]
Have you built your app using jdk 8? Somehow java time is not present in your app runtime.

**Comment by bahmanebazoo** [comment]
> Have you built your app using jdk 8? Somehow java time is not present in your app runtime.

![Screenshot from 2022-04-18 16-43-13](https://user-images.githubusercontent.com/37235324/163806749-baa8a2c8-950f-427d-aee8-24450799f4b0.png)

**Comment by anidotnet** [comment]
Verify if minSdkVersion is 26 or above

**Comment by bahmanebazoo** [comment]
> Verify if minSdkVersion is 26 or above. https://developer.android.com/reference/java/time/Instant.html

On sdk 26 or above is ok. it's on sdk 23 android 6.0.1

**Comment by anidotnet** [comment]
> Minsdk is 21 as NO2 document says

Have you found this specific version mentioned in nitirte documentation? Could you please point it out? I might need to correct it. The nitrite java library is compatible for api level 19, but potassium nitrite needs api level 26 by default.

Having said that, you can bypass that restriction also in case of potassium nitrite. You just have to set a custom nitrite mapper. See the logic here -  https://github.com/nitrite/nitrite-java/blob/9afef01caab7a647dd6b43bd147288b8d6264780/potassium-nitrite/src/main/kotlin/org/dizitart/kno2/Builder.kt#L130

One of such example is there in junit tests, where threetenbp library is used in place of java time - https://github.com/nitrite/nitrite-java/blob/9afef01caab7a647dd6b43bd147288b8d6264780/potassium-nitrite/src/test/kotlin/org/dizitart/kno2/BackportJavaTimeTest.kt#L40 Create your own `JacksonFacade` appropriately and you will be good to go.
