### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant; error in android 23

### ISSUE THREAD

**Issue by immohanravi** [nitrite/nitrite-java#745]
```java
2022-08-04 23:41:47.852 4805-4859/com.bogarsoft.anonymous E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.bogarsoft.anonymous, PID: 4805
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:119)
        at java.lang.Class.newInstance(Native Method)
        at java.util.ServiceLoader$ServiceIterator.next(ServiceLoader.java:214)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1105)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1089)
        at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1139)
        at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:83)
        at org.dizitart.no2.mapper.JacksonFacade.<init>(JacksonFacade.java:54)
        at org.dizitart.no2.mapper.JacksonMapper.<init>(JacksonMapper.java:41)
        at org.dizitart.no2.NitriteContext.getNitriteMapper(NitriteContext.java:162)
        at org.dizitart.no2.objects.DefaultObjectRepository.initRepository(DefaultObjectRepository.java:302)
        at org.dizitart.no2.objects.DefaultObjectRepository.<init>(DefaultObjectRepository.java:57)
        at org.dizitart.no2.objects.RepositoryFactory.open(RepositoryFactory.java:46)
        at org.dizitart.no2.Nitrite.getRepository(Nitrite.java:168)
        at com.bogarsoft.anonymous.App$onCreate$1.invokeSuspend(App.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4232b6b, Dispatchers.IO]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/com.bogarsoft.anonymous-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bogarsoft.anonymous-1/lib/x86, /data/app/com.bogarsoft.anonymous-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        	... 23 more
    	Suppressed: java.lang.ClassNotFoundException: java.time.Instant
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 24 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by anidotnet** [comment]
Would you care to provide more info on this exception? A reproducible code would be fine. Also mention what version of nitrite are you using.
