### ISSUE TITLE
NitriteBuilder#openOrCreate sometimes returns null

### ISSUE THREAD

**Issue by DarkAtra** [nitrite/nitrite-java#801]
I'm using nitrite in a side project of mine, namely: https://github.com/DarkAtra/v-rising-discord-bot

I've recently received a bug report for my bot and after tracking down the root cause it seems that, in some cases, the `NitriteBuilder` returns `null` when calling `openOrCreate`. Could you explain those edge cases and why you opted to returning null instead of throwing an exception? The resulting NPE was kinda hard to track down and it was also not really clear from the docs that the builder could ever return `null`.

Link to the initial bug report: https://discord.com/channels/993243434695540837/993243434695540839/1082189504837865492

**Comment by anidotnet** [comment]
I don't have access to the discord channel you have mentioned. Could you please paste the bug report here? And also please provide the stacktrace here.

**Comment by DarkAtra** [comment]
You can join here if you want: https://discord.gg/KcMcYKa6Nt
There's not too much information on it though.

The exception is:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'database' defined in class path resource [de/darkatra/vrising/discord/DatabaseConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dizitart.no2.Nitrite]: Factory method 'database' threw exception; nested exception is java.lang.NullPointerException: builder()
            .c?perties.databasePassword) must not be null
```

And i think the reason is that `NitriteBuilder` returns `null` in some cases (Line 544).

**Comment by anidotnet** [comment]
Remove the `compressed()` and try once.

**Comment by DarkAtra** [comment]
As i have not found a way to reproduce the error locally (yet) i'll create a pre release of the bot and ask the reporter to test if that fixes the issue. However, disabling compressions is something that i'd rather not do in the long run.

I also still think that the `NitriteBuilder` should never return `null` or at least that it should be documented somewhere in the javadocs.

**Comment by anidotnet** [comment]
If you look into the below code snippet, there might be one edge case where the underlying store could return null.

https://github.com/nitrite/nitrite-java/blob/9afef01caab7a647dd6b43bd147288b8d6264780/nitrite/src/main/java/org/dizitart/no2/NitriteBuilder.java#L451-L544

In a rare scenario, if the code in the first try block throws `IllegalStateException` and the db file is not locked, filePath is not empty string but at the same time the validation at line 476 fails and the database is not a readonly database, then the underlying MVStore variable `store` could be null.

Any idea how that could happen?

**Comment by DarkAtra** [comment]
I'm currently suspecting that it might be related to file system permissions. In OPs case, the bot is running as a docker container and the directory the database is in is a mounted volume. I'm still unsure when exactly the `IllegalStateException` would occur but i can imagine that if it occurred and the directory is not readable by the docker container, then we might find ourself in the edge case you described above. Could be something completely different though.

I'll continue trying to reproduce the issue locally so that i can debug ^^

**Comment by anidotnet** [comment]
I'll be waiting for your input. Based on the finding, I might have to provide a bugfix also.

**Comment by DarkAtra** [comment]
Ok, i just reproduced it locally by creating an empty directory with `600` permission (e.g. only owner can read/write). I then mounted said directory to the `/data` path the docker image is using and if fails with the same error message:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bot': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'database' defined in class path resource [de/darkatra/vrising/discord/DatabaseConfiguration.class]: Failed to instantiate [org.dizitart.no2.Nitrite]: Factory method 'database' threw exception with message: builder()
            .c?perties.databasePassword) must not be null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1344) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1188) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-3.0.4.jar:3.0.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-3.0.4.jar:3.0.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.0.4.jar:3.0.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.4.jar:3.0.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.4.jar:3.0.4]
	at de.darkatra.vrising.discord.BotKt.main(Bot.kt:73) ~[classes/:2.0.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[workspace/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[workspace/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[workspace/:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[workspace/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'database' defined in class path resource [de/darkatra/vrising/discord/DatabaseConfiguration.class]: Failed to instantiate [org.dizitart.no2.Nitrite]: Factory method 'database' threw exception with message: builder()
            .c?perties.databasePassword) must not be null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:491) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1324) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-6.0.6.jar:6.0.6]
	... 26 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dizitart.no2.Nitrite]: Factory method 'database' threw exception with message: builder()
            .c?perties.databasePassword) must not be null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.0.6.jar:6.0.6]
	... 40 common frames omitted
Caused by: java.lang.NullPointerException: builder()
            .c?perties.databasePassword) must not be null
	at de.darkatra.vrising.discord.DatabaseConfiguration.database(DatabaseConfiguration.kt:20) ~[classes/:2.0.4]
	at de.darkatra.vrising.discord.DatabaseConfiguration$$SpringCGLIB$$0.CGLIB$database$0(<generated>) ~[classes/:2.0.4]
	at de.darkatra.vrising.discord.DatabaseConfiguration$$SpringCGLIB$$2.invoke(<generated>) ~[classes/:2.0.4]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.6.jar:6.0.6]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.6.jar:6.0.6]
	at de.darkatra.vrising.discord.DatabaseConfiguration$$SpringCGLIB$$0.database(<generated>) ~[classes/:2.0.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.6.jar:6.0.6]
	... 41 common frames omitted
```

**Comment by anidotnet** [comment]
I'll put an error message at line 483 in the next release. Meantime, you can ask the OP to use a file system where he has proper permission.

**Comment by DarkAtra** [comment]
> I'll put an error message at line 483 in the next release. Meantime, you can ask the OP to use a file system where he has proper permission.

Sounds good. I already reached out to OP and asked for details. I'm certain that we'll get the bot up and running as soon as the permissions are fixed. Ty for the quick response!
