### ISSUE TITLE
MVStore claims to have unsaved changes after calling nitriteDatabase.getCollection(...)

### ISSUE THREAD

**Issue by chris9182** [nitrite/nitrite-java#901]
We are opening an existing database as follows:

```
 MVStoreModule storeModule = MVStoreModule.withConfig()
        .filePath(databaseLocation).readOnly(readOnly).build();
    NitriteBuilder builder = Nitrite.builder().loadModule(storeModule);
    return builder.openOrCreate(VALUE_PROPERTY_SOURCE_USER, password);
```

after this, we call

`nitriteDatabase.getCollection(COLLECTION_ELEMENTS)`

closing the nitriteDatabase then leads to an exception

> org.dizitart.no2.exceptions.NitriteIOException: Error occurred while committing the database
> 	at org.dizitart.no2.NitriteDatabase.commit(NitriteDatabase.java:204) ~[nitrite-4.2.0.jar:?]
> 	at org.dizitart.no2.NitriteDatabase.close(NitriteDatabase.java:177) ~[nitrite-4.2.0.jar:?]
> 	...
> 	...
> Caused by: org.h2.mvstore.MVStoreException: This store is read-only [2.2.224/2]
> 	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996) ~[h2-mvstore-2.2.224.jar:2.2.224]
> 	at org.h2.mvstore.MVStore.store(MVStore.java:804) ~[h2-mvstore-2.2.224.jar:2.2.224]
> 	at org.h2.mvstore.MVStore.commit(MVStore.java:778) ~[h2-mvstore-2.2.224.jar:2.2.224]
> 	at org.h2.mvstore.MVStore.commit(MVStore.java:770) ~[h2-mvstore-2.2.224.jar:2.2.224]
> 	at org.dizitart.no2.mvstore.NitriteMVStore.commit(NitriteMVStore.java:73) ~[nitrite-mvstore-adapter-4.2.0.jar:?]
> 	at org.dizitart.no2.NitriteDatabase.commit(NitriteDatabase.java:202) ~[nitrite-4.2.0.jar:?]
> 	... 13 more

What I found was that the following code:
```
    System.err.println(nitriteDatabase.hasUnsavedChanges());
    nitriteDatabase.getCollection(COLLECTION_ELEMENTS);
    System.err.println(nitriteDatabase.hasUnsavedChanges());
```
    
returns first false then true.

Note that the collection in this example already exists in the database. I.e. `nitriteDatabase.hasCollection(COLLECTION_ELEMENTS)` returns true before the abovementioned code.

**Comment by chris9182** [comment]
Also, we saw that autoCompact is no longer an option that can be set in the MVStoreModule and there is no manual call to compact either anymore. Is this a deliberate decision?

**Comment by anidotnet** [comment]
At a first glance its look like a config issue in your code. The error message says,

```
Caused by: org.h2.mvstore.MVStoreException: This store is read-only [2.2.224/2]
...
```

In the builder, you are setting,

```
MVStoreModule storeModule = MVStoreModule.withConfig()
        .filePath(databaseLocation)
        .readOnly(readOnly)  <-----
        .build();
```

I believe, you are opening the db in readonly mode, where no changes to the collection will be saved. That's the reason why you are getting the error.

Regarding `autoCompact`, it was a deliberate decision, as this MVStore feature is buggy, so I omitted it in the new version.

**Comment by chris9182** [comment]
I did intentionally open the db in read only mode. Is nitriteDatabase.getCollection() not supported when using read-only mode? How else would I access the data when opening in read-only mode?

**Comment by anidotnet** [comment]
Ok, I need to check that.

**Comment by anidotnet** [comment]
@chris9182 the changes are in latest 4.2.1-SNAPSHOT. Please check and report back in case you are still seeing the issue.
