### ISSUE TITLE
Invalid repository type for entity where all fields are nullable (with JacksonMapperModule)

### ISSUE THREAD

**Issue by magicDGS** [nitrite/nitrite-java#912]
When using a entity with jackson-annotatiosn including only the non-empty values, the `Nitrite::getRepository` mehtod does throw the following exception (with the `JacksonMapperModule` provided):

```java
org.dizitart.no2.exceptions.ValidationException: Invalid repository type

	at org.dizitart.no2.common.util.ValidationUtils.validateRepositoryType(ValidationUtils.java:170)
	at org.dizitart.no2.repository.RepositoryFactory.createRepository(RepositoryFactory.java:139)
	at org.dizitart.no2.repository.RepositoryFactory.getRepository(RepositoryFactory.java:79)
	at org.dizitart.no2.repository.RepositoryFactory.getRepository(RepositoryFactory.java:53)
	at org.dizitart.no2.NitriteDatabase.getRepository(NitriteDatabase.java:73)
	at io.github.ygojson.tools.dataprovider.impl.repository.nitrite.NitriteJsonProblem.test(NitriteJsonProblem.java:24)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.dizitart.no2.exceptions.ValidationException: Cannot convert to document from type class io.github.ygojson.tools.dataprovider.impl.repository.nitrite.NitriteJsonProblem$TestEntity
	at org.dizitart.no2.common.util.ValidationUtils.validateRepositoryType(ValidationUtils.java:167)
	... 8 more
```

## Use case

Sometimes the project doesn't have access to the definition of the models to be used in serialization.
The possible workarounds are not acceptable from my POV:

- Wrap/Unwrap the object: any action performed on a repository should wrap/unwraps the object, meaning extra processing time (creating the object and calling the getter)
- Provide a jackson-module that serializes everything: this means that documents would be stored with `null`, meaning that serialize/deserialize the document would take extra time in addition to the instantiation to the entity-object.

## Repro scenario

Here is a test class with a repro scenario on a test:

```java
public class NitriteJsonProblem {

	@Test
	void test() {
		final Nitrite nitrite = Nitrite.builder()
			.loadModule(new JacksonMapperModule())
			.openOrCreate();

		nitrite.getRepository(TestEntity.class);
	}

	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	private static class TestEntity {
		@Id
		@JsonProperty("id")
		UUID id;
		@JsonProperty("name")
		String name;
	}
}
```

**Comment by anidotnet** [comment]
`JacksonMapperModule` is working as expected here. The culprit here is the annotation - `@JsonInclude(JsonInclude.Include.NON_EMPTY)`. You are instructing the internal `ObjectMapper` to ignore all null fields. This is resulting an empty document while validating the entity. Remove the annotation and you will be good. 

On another note, if you don't have access to the model definition, you can take a look into the `EntityConverter` [here](https://nitrite.dizitart.com/java-sdk/repository/mapper/index.html#entityconverter). And also try to avoid use the same model definition for your presentation layer and persistence layer if you are doing it already.

**Comment by anidotnet** [comment]
The purpose of the entity validation before opening an object repository is to check if the entity type 

- Is not a value type
- Is not a wrapper object
- Not an array type
- Has at-least one user defined field

This conditions are applicable for all types of `NitriteMapper` implementations. 

In case of `@JsonInclude(JsonInclude.Include.NON_EMPTY)` in your example, the `JacksonMapper` is creating an empty document like - `{}` which fails the condition - *Has at-least one user defined field*. This condition is to ensure that an object repository does not contain a bunch of empty documents (if you really need such, use `NitriteCollection` instead).

Instead of `{}` what Nitrite expecting is kind of a skeleton document where all fields are there but no values:

```json
{
     "id": null,
     "name": null
}
```

I hope, this clear your confusion.
