### ISSUE TITLE
org.dizitart.no2.common.tuples.Pair cannot be cast to class java.lang.Comparable

### ISSUE THREAD

**Issue by Dacesilian** [nitrite/nitrite-java#947]
Hello,

I'm using version 4.2.2, my class is defined as below. When I want to insert new entity converted to Document using Repository, error occurres.

```
@Indices({
        @Index(fields = {"id"}, type = IndexType.UNIQUE),
})
public class MyItem implements Serializable {

    @Id
    private NitriteId id;
```

Can you please tell me if is it error or what should I change? Thank you.

```
java.lang.ClassCastException: class org.dizitart.no2.common.tuples.Pair cannot be cast to class java.lang.Comparable (org.dizitart.no2.common.tuples.Pair is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')
	at org.dizitart.no2.index.SingleFieldIndex.write(SingleFieldIndex.java:87)
	at org.dizitart.no2.index.ComparableIndexer.writeIndexEntry(ComparableIndexer.java:70)
	at org.dizitart.no2.collection.operation.DocumentIndexWriter.writeIndexEntryInternal(DocumentIndexWriter.java:97)
	at org.dizitart.no2.collection.operation.DocumentIndexWriter.writeIndexEntry(DocumentIndexWriter.java:50)
	at org.dizitart.no2.collection.operation.WriteOperations.insert(WriteOperations.java:99)
	at org.dizitart.no2.collection.operation.CollectionOperations.insert(CollectionOperations.java:98)
	at org.dizitart.no2.collection.DefaultNitriteCollection.insert(DefaultNitriteCollection.java:98)
	at org.dizitart.no2.collection.DefaultNitriteCollection.insert(DefaultNitriteCollection.java:54)
	at org.dizitart.no2.repository.DefaultObjectRepository.insert(DefaultObjectRepository.java:112)
```

Error is in casting to Comparable `new DBValue((Comparable<?>) item)` when iterating.
```
@Override
    public void write(FieldValues fieldValues) {
        Fields fields = fieldValues.getFields();
        List<String> fieldNames = fields.getFieldNames();

        String firstField = fieldNames.get(0);
        Object element = fieldValues.get(firstField);

        NitriteMap<DBValue, List<?>> indexMap = findIndexMap();

        if (element == null) {
            addIndexElement(indexMap, fieldValues, DBNull.getInstance());
        } else if (element instanceof Comparable) {
            // wrap around db value
            DBValue dbValue = new DBValue((Comparable<?>) element);
            addIndexElement(indexMap, fieldValues, dbValue);
        } else if (element.getClass().isArray()) {
            Object[] array = convertToObjectArray(element);

            for (Object item : array) {
                // wrap around db value
                DBValue dbValue = item == null ? DBNull.getInstance() : new DBValue((Comparable<?>) item);
                addIndexElement(indexMap, fieldValues, dbValue);
            }
        } else if (element instanceof Iterable) {
            Iterable<?> iterable = (Iterable<?>) element;

            for (Object item : iterable) {
                // wrap around db value
                DBValue dbValue = item == null ? DBNull.getInstance() : **new DBValue((Comparable<?>) item)**;
                addIndexElement(indexMap, fieldValues, dbValue);
            }
        }
    }
```

**Comment by anidotnet** [comment]
It's hard to tell what is wrong without seeing the whole entity or what you are doing with the entity.

On a first glance, you can not create index in `NitriteId` field. This field is to retrieve the underlying id of the document.

Also, you should either use `@Id` or `@Index` on a particular non-NitriteId field(s).

After this change if the issue is still not resolved, please provide a small reproducible code.

**Comment by anidotnet** [comment]
Are you indexing `otherField`? If not, then probably that is not the source of the error. The error happened in single field indexer. So look into your indexed fields while debugging the issue.
