### ISSUE TITLE
`Chunk not found` exception when trying to drop index

### ISSUE THREAD

**Issue by AngryGami** [nitrite/nitrite-java#977]
I'm getting following exception when trying to drop index
```
org.h2.mvstore.MVStoreException: Chunk 616 not found [2.2.224/9]
       at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
       at org.h2.mvstore.FileStore.getChunk(FileStore.java:2006)
       at org.h2.mvstore.FileStore.readPage(FileStore.java:1953)
       at org.h2.mvstore.MVStore.readPage(MVStore.java:1021)
       at org.h2.mvstore.MVMap.readPage(MVMap.java:632)
       at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:657)
       at org.h2.mvstore.MVMap.setRootPos(MVMap.java:642)
       at org.h2.mvstore.MVStore.openMap(MVStore.java:479)
       at org.h2.mvstore.MVStore.openMap(MVStore.java:426)
       at org.h2.mvstore.MVStore.openMap(MVStore.java:405)
       at org.dizitart.no2.mvstore.NitriteMVStore.openMap(NitriteMVStore.java:112)
       at org.dizitart.no2.index.SingleFieldIndex.findIndexMap(SingleFieldIndex.java:166)
       at org.dizitart.no2.index.SingleFieldIndex.drop(SingleFieldIndex.java:129)
       at org.dizitart.no2.index.ComparableIndexer.dropIndex(ComparableIndexer.java:83)
...
```
I understand that my db is probably corrupted and I could just delete db file and start from scratch but I believe there must be less destructive way. I don't want to loose everything else in db just because one index is corrupted.

**Comment by anidotnet** [comment]
Hi @AngryGami did you try rebuilding index instead of dropping it, if you think the index is corrupted? 

> why do `openMap` here? MVStore is totally capable of removing map by just name

Inside the MVStore, it is opening the map by name anyway if it's not already opened. And `openMap` has no overhead in Nitrite if the MV map is already opened.

**Comment by anidotnet** [comment]
> It only goes inside openMap method if getMap returns null and I hoped that map was already opened at this point somehow.

That's what I said (Inside the MVStore, it is opening the map by name anyway if it's not already opened). If the map is already opened, `removeMap(String)` is calling `removeMap(MVMap)` and if the map is not opened, it is first opened in `removeMap(String)` and then call `removeMap(MVMap)`. Essentially, you can't avoid the situation you are currently in even if `removeMap(String)` is used.

Now back to the problem itself. As this kind of issue is almost impossible to reproduce, I need your help here in debugging it. Here is the [branch](https://github.com/nitrite/nitrite-java/tree/fix/977) which contains a slightly modified `NitriteMVStore` which tries to open the map with previous version if the db is corrupted. I am not sure if it will solve your issue, but as I said, I have no means to reproduce this issue and test the fix myself.

After cloning the repo branch to your local, just do a `mvn clean install` (may be change the pom version before) and use it in your project and see if the fix resolves the issue.
